packageExtensions:
  "@angular-eslint/schematics@*":
    dependencies:
      "@angular-devkit/core": "*"
      "@angular-devkit/schematics": "*"
      "@angular/cli": "*"
    peerDependencies:
      eslint: "*"
      typescript: "*"